<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Contrat extends \App\Entity\Contrat implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Contrat' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Contrat' . "\0" . 'num_contrat', '' . "\0" . 'App\\Entity\\Contrat' . "\0" . 'nom_user', '' . "\0" . 'App\\Entity\\Contrat' . "\0" . 'prenom_user', '' . "\0" . 'App\\Entity\\Contrat' . "\0" . 'num_tel', '' . "\0" . 'App\\Entity\\Contrat' . "\0" . 'code_postal', '' . "\0" . 'App\\Entity\\Contrat' . "\0" . 'ville', '' . "\0" . 'App\\Entity\\Contrat' . "\0" . 'destinataire', '' . "\0" . 'App\\Entity\\Contrat' . "\0" . 'type_contrat', '' . "\0" . 'App\\Entity\\Contrat' . "\0" . 'date', '' . "\0" . 'App\\Entity\\Contrat' . "\0" . 'nature_contart', '' . "\0" . 'App\\Entity\\Contrat' . "\0" . 'contrat', '' . "\0" . 'App\\Entity\\Contrat' . "\0" . 'demandeContart'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Contrat' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Contrat' . "\0" . 'num_contrat', '' . "\0" . 'App\\Entity\\Contrat' . "\0" . 'nom_user', '' . "\0" . 'App\\Entity\\Contrat' . "\0" . 'prenom_user', '' . "\0" . 'App\\Entity\\Contrat' . "\0" . 'num_tel', '' . "\0" . 'App\\Entity\\Contrat' . "\0" . 'code_postal', '' . "\0" . 'App\\Entity\\Contrat' . "\0" . 'ville', '' . "\0" . 'App\\Entity\\Contrat' . "\0" . 'destinataire', '' . "\0" . 'App\\Entity\\Contrat' . "\0" . 'type_contrat', '' . "\0" . 'App\\Entity\\Contrat' . "\0" . 'date', '' . "\0" . 'App\\Entity\\Contrat' . "\0" . 'nature_contart', '' . "\0" . 'App\\Entity\\Contrat' . "\0" . 'contrat', '' . "\0" . 'App\\Entity\\Contrat' . "\0" . 'demandeContart'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Contrat $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getNumContrat(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumContrat', []);

        return parent::getNumContrat();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumContrat(string $num_contrat): \App\Entity\Contrat
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumContrat', [$num_contrat]);

        return parent::setNumContrat($num_contrat);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomUser(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomUser', []);

        return parent::getNomUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomUser(string $nom_user): \App\Entity\Contrat
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomUser', [$nom_user]);

        return parent::setNomUser($nom_user);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrenomUser(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrenomUser', []);

        return parent::getPrenomUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrenomUser(string $prenom_user): \App\Entity\Contrat
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrenomUser', [$prenom_user]);

        return parent::setPrenomUser($prenom_user);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumTel(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumTel', []);

        return parent::getNumTel();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumTel(string $num_tel): \App\Entity\Contrat
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumTel', [$num_tel]);

        return parent::setNumTel($num_tel);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodePostal(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodePostal', []);

        return parent::getCodePostal();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodePostal(int $code_postal): \App\Entity\Contrat
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodePostal', [$code_postal]);

        return parent::setCodePostal($code_postal);
    }

    /**
     * {@inheritDoc}
     */
    public function getVille(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVille', []);

        return parent::getVille();
    }

    /**
     * {@inheritDoc}
     */
    public function setVille(string $ville): \App\Entity\Contrat
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVille', [$ville]);

        return parent::setVille($ville);
    }

    /**
     * {@inheritDoc}
     */
    public function getDestinataire(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDestinataire', []);

        return parent::getDestinataire();
    }

    /**
     * {@inheritDoc}
     */
    public function setDestinataire(string $destinataire): \App\Entity\Contrat
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDestinataire', [$destinataire]);

        return parent::setDestinataire($destinataire);
    }

    /**
     * {@inheritDoc}
     */
    public function getTypeContrat(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTypeContrat', []);

        return parent::getTypeContrat();
    }

    /**
     * {@inheritDoc}
     */
    public function setTypeContrat(string $type_contrat): \App\Entity\Contrat
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTypeContrat', [$type_contrat]);

        return parent::setTypeContrat($type_contrat);
    }

    /**
     * {@inheritDoc}
     */
    public function getDate(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDate', []);

        return parent::getDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setDate(\DateTimeInterface $date): \App\Entity\Contrat
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDate', [$date]);

        return parent::setDate($date);
    }

    /**
     * {@inheritDoc}
     */
    public function getNatureContart(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNatureContart', []);

        return parent::getNatureContart();
    }

    /**
     * {@inheritDoc}
     */
    public function setNatureContart(string $nature_contart): \App\Entity\Contrat
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNatureContart', [$nature_contart]);

        return parent::setNatureContart($nature_contart);
    }

    /**
     * {@inheritDoc}
     */
    public function getContrat(): ?\App\Entity\Contrat
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContrat', []);

        return parent::getContrat();
    }

    /**
     * {@inheritDoc}
     */
    public function setContrat(?\App\Entity\Contrat $contrat): \App\Entity\Contrat
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContrat', [$contrat]);

        return parent::setContrat($contrat);
    }

    /**
     * {@inheritDoc}
     */
    public function getDemandeContart(): ?\App\Entity\DemandeContart
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDemandeContart', []);

        return parent::getDemandeContart();
    }

    /**
     * {@inheritDoc}
     */
    public function setDemandeContart(?\App\Entity\DemandeContart $demandeContart): \App\Entity\Contrat
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDemandeContart', [$demandeContart]);

        return parent::setDemandeContart($demandeContart);
    }

    /**
     * {@inheritDoc}
     */
    public function setId(int $id): \App\Entity\Contrat
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

}
