<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNJQBCdB\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNJQBCdB/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNJQBCdB.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNJQBCdB\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerNJQBCdB\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'NJQBCdB',
    'container.build_id' => 'dacd4172',
    'container.build_time' => 1638521603,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNJQBCdB');
