<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHRNDKMy\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHRNDKMy/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHRNDKMy.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHRNDKMy\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerHRNDKMy\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'HRNDKMy',
    'container.build_id' => '410d1a0d',
    'container.build_time' => 1639057224,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHRNDKMy');
